### ISSUE TITLE
SCRIPT1003: Expected ':' ActivityModule.js (259,24)

### ISSUE THREAD

**Issue by RVohs** [CustomerFX/FX.ActivityModule.JS#1]
Testing module using the Sample CustomConfigurations.js(see the ReadMe.md).
There's something about the FXActivity/ActivityModule.js at line 259:
        _setConfigValue(config, key, defaultValue) {
            if (!config.hasOwnProperty(key)) {
                config[key] = defaultValue;
            }
        },
MSkB: https://docs.microsoft.com/en-us/scripting/javascript/misc/expected-colon

**Comment by RyanFarley** [comment]
Thank you. It's been fixed.
